server:
  port: 8081
  servlet:
    contextPath: /api
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/galactic_pictures
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
        sql:
          BasicBinder: TRACE
  file:
    name: app.log
    path: .