#spring:
#  profiles:
#    active: dev

java:
  runtime:
    version: 11
server:
  port: 8081
  servlet:
    contextPath: /api
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/galactic_pictures
    username: yoyo
    password: Kercode4
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root:
      root: WARN
    org:
      hibernate:
        SQL: DEBUG
        sql:
          BasicBinder: TRACE
  file:
    name: log/app.log