server:
  port: 8081
  servlet:
    contextPath: /api
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:galactic_picture
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        sql:
          BasicBinder: TRACE